server:
  port: 8080
  tomcat:
    accept-count: 100

spring:
  application:
    name: order-service

management:
  endpoints:
    web:
      exposure:
        include: health,info

inventory:
  base-url: ${INVENTORY_BASE_URL:http://localhost:8081}
  connect-timeout: 1s
  read-timeout: 2s