server:
  port: 8081

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5432/thesis_inventory
    username: ${DB_USERNAME:thesis}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

otel:
  # Keep every trace in the thesis experiment.
  traces:
    sampler: always_on
    exporter: otlp

  # The Spring Boot starter uses HTTP/protobuf by default.
  # We explicitly choose gRPC because Collector:4317 is OTLP/gRPC.
  exporter:
    otlp:
      protocol: grpc
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}

  # Day 3 is about tracing only.
  # Do not send metrics/logs to the Collector yet.
  metrics:
    exporter: none

  logs:
    exporter: none

  # Explicitly keep the important instrumentations enabled.
  instrumentation:
    jdbc:
      enabled: true

    spring-web:
      enabled: true

    spring-webmvc:
      enabled: true